'use strict'

const INCREASE_SCORE = 'INCREASE_SCORE'
const SET_NAME = 'SET_NAME'
const SET_VEHICLE = 'SET_VEHICLE'
const RESET_STATS = 'RESET_STATS'
const SET_TIME = 'SET_TIME'
const SET_TRIPS = 'SET_TRIPS'
const SET_GOLD = 'SET_GOLD'
const SET_DISTANCE = 'SET_DISTANCE'

export {
    INCREASE_SCORE,
    SET_NAME,
    SET_VEHICLE,
    RESET_STATS,
    SET_TIME,
    SET_TRIPS,
    SET_GOLD,
    SET_DISTANCE
}